TRAINING_DEFAULT_MAIN_OBJECTIVE='Основаная цель'
TRAINING_DEFAULT_TASKS=['Задача 1', 'Задача 2']
EXERCISE_GROUP_NAME_BY_ID={
    1:'A',
    2:'B',
    3:'C',
    4:'D'
}
EXERCISE_GROUP_NAME_UNKNOWN='X'
